// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang_2380600870.Models;

#nullable disable

namespace WebBanHang_2380600870.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311131328_AddSubscribers")]
    partial class AddSubscribers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Occasion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Trà & Thảo Mộc"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cà Phê"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bánh Sáng"
                        });
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Hoa cúc hữu cơ dịu nhẹ, pha cùng mật ong rừng địa phương và một chút vani.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCEAjGgjkSer5q9ba5D6NyzN1c9lTOJPMXWpNJltT_GLw0NEh93dsoZsJaXB20ZNlnBukK0BvyNWGB6fwjYu-mP17nG4ALpaDwiVOTRHcQvCf1w1Ib5UbFX9y76GFKvPekabC6V_VgoEm-Zc1Y_S96uZErX-tYH5XAeDCbc7TxftVTD-rmBHuOd7aSkx881C8NtH-mc5rMhj4dyuSomr4y-1PPGwQdiN893dwpZjGmWyehq9XIq_Ba8NDWvScXE1Tf9RBlP3LwPkGkJ",
                            Name = "Trà Hoa Cúc Mật Ong",
                            Price = 55000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cánh atiso đỏ giàu vitamin, kết hợp hoa hồng Bulgaria khô cho hương thơm thanh nhẹ.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBquJBlkgANzMfyJGh1XkspjUt3umtwxQzexDd8I0mt0FgPpx6FXkExK_M7Xm-wM6-LP7BG6Uy4DlU4Zs_SLn4nniVk8-ZjKvOweTbUCwoZ4qlVJ3Ng2_hYfQ3E6HoYycQvSScsSUO1HRJnZF3sizIF_rZ_Dy-byN31UV3fduUnRR-A1zsaH7m7UztM6dHj1VAVWReoWicfHForfNH45bxgCGWHUAofQXMqeY9jauQltovivmnmKywndNVfLUxF3nPKs7Lg3ozOwc5Re",
                            Name = "Trà Hoa Atiso Đỏ",
                            Price = 58000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Trà đen thượng hạng ướp tinh dầu bergamot và cánh hoa ngô xanh — cổ điển và tinh tế.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuD-HrH2opygixRAPA4_hKWugp4IUUWQdv8LY4AAqkAJ4eUISM5MqQu2ZqCQaD_fj6h5ujbIB7gwlMDgzTEGuN5-L7j_J49jf5Y6my037ZvILcU-yaOt5EGfRdq-mRf5ILDr5o8oYHvOHa4-EBvZbGfClfC1TQjlYMdoHZWYEb7qY9tlI0CbLCoHI4MXnOdGG8P02A8BEg1Y9ZhMI8m8EC_B-7UvsW1IxAKATnSeQzc2Iava4vUQGKDILPm_YIYx-pZDsddI8-ILgzY6",
                            Name = "Earl Grey Hoàng Gia",
                            Price = 55000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Trà xanh cuộn tay, ướp hoa lài tươi nhiều lần — hương thơm dịu mà sâu lắng.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDQqi2HYPgIa_kB6UkOUsv1ob9VljdNcRiPmydMW8pDePwjEl8EvWaBKZd6VTeetyXv31Jee_gx0IAf5xy6B129-6OEQNi9FUFN42I4CkNVtsJrZGES7TJSBdXDHFauYzCKd1YEq1oUKfqEsfs8n-n0sw2wy7TzjnveLWlJLQyBiw-geTWQg_J8kRLA7hpIo5euMXC5oppW3jMTIKImMRauGsxp1-19-wTW6LG1IosZWTlhpYXUMLc58UBBXuKlsIxRHhTJuu-0i5oU",
                            Name = "Trà Lài Ngọc Châu",
                            Price = 65000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Robusta đậm đà, phủ lớp lòng đỏ trứng đánh bông cùng sữa đặc — đặc sản không thể thiếu.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBtk6EC-fylhVI5xH_hiJ8RDZU-69cXHO2s1AehaDaLNDlCJYITX2Zxb1Z9FjqLPonF1rKl5UbilrIOwd10DxLcnVcB1sYqKd-q-cBzkMML0GEQK84wxT31BEbpLz89Raqu3e8S6B6y6eyfYz8NMNZ6uy86k8v6sEjh0KsoEA_9mz8VGql5gajQZ0kafubfK55b95S9AjEflczQl7mYmLhBnNE6M70ea_tSmPbAHHcZTKFHTypRezqxN7Cm--NywSQi8Su4cmDVEECJ",
                            Name = "Cà Phê Trứng Hà Nội",
                            Price = 65000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Blend Arabica & Robusta, chiết xuất chuẩn mực — crema vàng óng, đậm mà không gắt.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuBAgg0VukbL8PkMBh630VrgmEo5GlHTpzYcPsve8JYTreMPfDcsUXIpEGgQxW_Mw_xFs2A7aPigCqb8WBVfvYVbkQRIfQPihVRu9nSX8LVqBRs9-Bx-EfvJPEypDdb9Eh2IsKp9QGrGb-Ltj40PMoFo15yqvF2Vgf6mwzVUQ9f52k5I_UIbONcIO9eWA9PwlzcgN8OJR38B-a5VQ-CXMapEAYOQf3-ibyb8jEm4anTRkFjkDMIoZkEEOBTMLQzS0d8SfCcvfAX_0qKO",
                            Name = "Espresso Truyền Thống",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Ủ lạnh suốt 18 tiếng — vị mượt mà, ít đắng, thoảng hương sô-cô-la nhẹ nhàng.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuAmJUt1qccm5508I5vD_7QhOCniGdlCnerKYHZODhzkWxHJIA_t1SglSieq6JrPBXjg0YRwJjOIHzaOhaFNsdpo5mt7bABv4IHhr2iFalxHhNNpghXL3EFetndNXXGE0AHca9SvXHiTeroRThJ7BlNPHifK1w01nGqKZ4eFo5mDoYOy6hp-ozZpOBnEC4yJRCbrCkxAmYn2Q8lCulkG1zehU5QCcNhiciqPVQSKmkDozC9BtdGSfRAGLxqbSOO6xXQk4iCT6-5RAb_r",
                            Name = "Cold Brew 18 Giờ",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Sữa tươi đánh bọt mịn như nhung, rót trên hai shot espresso — thêm chút quế cho ấm lòng.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuAtK1_y4hfIsSD370bZL11idnq18mh0bc-3O46w-21oCAtSxTFfm17M9PS-ii40W8IhN967PdrnBbmx5P4Ra2fYE4vQCZ99yVEEWSXMCnw4Fltbt_F8pBkmhOEfDtILMliJIzUQ0pOult2Rm8kqS2WR-p7MxwYFeInvMr8vCXChS_YafKfUERTuBmkmpE6fc7zxbuUFXv3u4s3QEXLmUWB1RJtPU2-4tPeNr-CkaBdM21mDlNgrLLo06F_Nd08Bw5PsEuxutMyn6316",
                            Name = "Latte Nhung",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Nướng hai lần, nhân kem hạnh nhân, rắc hạnh nhân lát lên trên — giòn tan và thơm lừng.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuDuXIB-ebcP8NsQJpZGJoF555uRr-TrEgQ_s7NJOUSSS9-HqIXFAHZeJtkttWZfQ8sPueSPg_0ws4eiuadUjFUW1N1ErYvkqhQPGgGsdAssgzGXgux5wXpORtpK6Bduqw8IeBZaJIRfArYsKVdSUGAEYh8H4FOgRHP9y3AaqLGZB9n8_0h40-m73xcy2x0UN60LDpOZicMQpeHKmAFax9Nee9jXF_z6gJSvMaXf7cv2qln-xesVIxQazR1xqZrIUgUNI5mg7IqRGeFF",
                            Name = "Croissant Hạnh Nhân",
                            Price = 38000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Mứt trái cây theo mùa trên nền bánh ngàn lớp giòn rụm, phủ kem trứng vani nhẹ nhàng.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCN56R6kgmsS-aVc-eplM5QDI5vQHrjwyeV_szA7HBIFtj7td95uvjPXEvW4uyTU7U5Ef28-H4FAVRwr4A-a-X-Hj_K7UJzCGI_f6_Zw7TEBi23Feimclr93XrVM_PtHX6dkj_UcpWRBbZ8Jd9EFslVSFsxJi_Ltzo-xPWPVgFOt9S1WSvMq1a6alIAMS5-apdbb34SRWlJVU36erUQCTZx05UgWKz1YQKeB1GEhRHjRPUqsK2mn2UWGTfw6JUduGg6WZnmrDJ1xksr",
                            Name = "Bánh Trái Cây Mùa",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Hai lát bánh mì chua thủ công nướng vàng, ăn kèm bơ lên men và mứt dâu rừng tự làm.",
                            ImageUrl = "https://lh3.googleusercontent.com/aida-public/AB6AXuCFGhQ6PA3PWH7EXeIIw2LwXxKOZWXr6dCzy4iM9UAn8xYcbuUD1uqhYNyQtgzpaavc1tbDt9e11zg6xyih5kuREdjtIqAbcWio4BqKpJ1n4kFpCf8cutPqkeSukUSnvRlNXOCKP_h0h95C2E0Qp89eRaZRbyGSgjL1OUEgnMjmQ4iEeYILEp4uDy0jmrYhv4S4xRUbiYbJmIvsfvRTbI2JkYBZVYWe1_YZLIiq3xokHn46ysYFenexcGQiICdUHPPph4ZuUiwWzipa",
                            Name = "Bánh Mì Chua & Mứt",
                            Price = 42000m
                        });
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang_2380600870.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Order", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang_2380600870.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Product", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.ProductImage", b =>
                {
                    b.HasOne("WebBanHang_2380600870.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebBanHang_2380600870.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
